server.port=8443
server.address=0.0.0.0
server.ssl.enabled=true
server.ssl.key-store=file:/opt/servidorspringsebastian/keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=arep12
server.ssl.key-alias=tomcat

spring.datasource.url=jdbc:h2:file:/opt/servidorspringsebastian/data/testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true


logging.level.org.springframework=INFO
